spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:600000}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_JWKS_URI}
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION_KEY}
  bucket: ${AWS_BUCKET_KEY}
