spring:
  application:
    name: MS-MERCADO-PAGO
mp-config:
  url-mercado-pago: https://api.mercadopago.com
  access-token: ${AccessToken}
  public-key: ${PublicKey}
back-urls:
  success: ${UrlSuccess:http://localhost:8080/mercado-pago/success}
  failure: ${UrlFailure:http://localhost:8080/mercado-pago/failure}
  pending: ${UrlPending:http://localhost:8080/mercado-pago/pending}
api:
  order: http://localhost:8060/
auth:
  url: http://localhost:9095
  service-name: MS-MERCADO-PAGO
  api-key: ${AuthApiKey:297378c3-4cea-465e-b321-bd0221f987b0}

url:
  notification: https://keesha-velutinous-sufficiently.ngrok-free.dev/webhook-test