include:
  - ./networks/network.yml

services:

  config:
    extends:
      file: ./services/config/docker-compose.yml
      service: config

  auth-public:
    extends:
      file: ./services/auth-public/docker-compose.yml
      service: auth-public
    depends_on:
      config:
        condition: service_healthy

  catalog:
    extends:
      file: ./services/catalog/docker-compose.yml
      service: catalog
    depends_on:
      config:
        condition: service_healthy
      redis:
        condition: service_started
      auth-public:
        condition: service_started

  gateway:
    extends:
      file: ./services/gateway/docker-compose.yml
      service: gateway
    depends_on:
      auth-public:
        condition: service_started
      catalog:
        condition: service_started

  order:
    extends:
      file: ./services/order/docker-compose.yml
      service: order
    depends_on:
      config:
        condition: service_healthy
      auth-public:
        condition: service_started
      catalog:
        condition: service_started

  mercado-pago:
    extends:
      file: ./services/mercado-pago/docker-compose.yml
      service: mercado-pago
    depends_on:
      config:
        condition: service_healthy
      order:
        condition: service_started
      auth-public:
        condition: service_started

  ngrok:
    extends:
      file: ./services/ngrok/docker-compose.yml
      service: ngrok
    depends_on:
      mercado-pago:
        condition: service_started

  redis:
    extends:
      file: ./services/redis/docker-compose.yml
      service: redis

  n8n:
    extends:
      file: ./services/n8n/docker-compose.yml
      service: n8n
    depends_on:
      auth-public:
        condition: service_started
      order:
        condition: service_started

networks:
  dtt-network:
    name: dtt-network
    driver: bridge

volumes:
  redis-data:
  n8n_data: